### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [btd1337/iguanidae-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by btd1337** [comment]
@unixorn Done in https://github.com/btd1337/iguanidae-zsh-theme/commit/328634efc65b7fccef1332f032c0ee6a3f2682e2. Thanks!

**Comment by unixorn** [comment]
Added in https://github.com/unixorn/awesome-zsh-plugins/pull/802, thanks
